### ISSUE TITLE
BMO Crashing when deleting a control plane node

### ISSUE THREAD

**Issue by Xenwar** [metal3-io/baremetal-operator#377]
When running the following scripts from Metal-dev environment, the BMO is crashing and stays down for a while. 
```
./scripts/v1alpha2/create_controlplane.sh 
# Wait for a while
./scripts/v1alpha2/delete_controlplane.sh 
```
BMO logs shown below
```
{"level":"info","ts":1577430729.4292197,"logger":"cmd","msg":"Go Version: go1.10.8"}
{"level":"info","ts":1577430729.4307537,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1577430729.431537,"logger":"cmd","msg":"Version of operator-sdk: v0.12.0"}
{"level":"info","ts":1577430729.4318814,"logger":"cmd","msg":"Component version: metal3-io/baremetal-operator was not built with version info"}
{"level":"info","ts":1577430729.928501,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":"127.0.0.1:8085"}
{"level":"info","ts":1577430729.928687,"logger":"cmd","msg":"Registering Components."}
{"level":"info","ts":1577430729.9287965,"logger":"baremetalhost_ironic","msg":"ironic settings","endpoint":"http://172.22.0.2:6385/v1/","inspectorEndpoint":"http://172.22.0.2:5050/v1/","deployKernelURL":"http://172.22.0.2:6180/images/ironic-python-agent.kernel","deployRamdiskURL":"http://172.22.0.2:6180/images/ironic-python-agent.initramfs"}
{"level":"info","ts":1577430729.9296534,"logger":"cmd","msg":"Starting the Cmd."}
I1227 07:12:09.929819       1 leaderelection.go:241] attempting to acquire leader lease  metal3/baremetal-operator...
{"level":"info","ts":1577430729.9307973,"logger":"controller-runtime.manager","msg":"starting metrics server","path":"/metrics"}
I1227 07:12:27.386550       1 leaderelection.go:251] successfully acquired lease metal3/baremetal-operator
{"level":"info","ts":1577430747.3877852,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"metal3-baremetalhost-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1577430747.5017076,"logger":"controller-runtime.controller","msg":"Starting EventSource","controller":"metal3-baremetalhost-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1577430747.6103277,"logger":"controller-runtime.controller","msg":"Starting Controller","controller":"metal3-baremetalhost-controller"}
{"level":"info","ts":1577430747.6105263,"logger":"controller-runtime.controller","msg":"Starting workers","controller":"metal3-baremetalhost-controller","worker count":1}
{"level":"info","ts":1577430747.610987,"logger":"baremetalhost","msg":"Reconciling BareMetalHost","Request.Namespace":"metal3","Request.Name":"node-0"}
{"level":"info","ts":1577430747.6115873,"logger":"baremetalhost","msg":"provisioning","Request.Namespace":"metal3","Request.Name":"node-0","provisioningState":"provisioning"}
{"level":"info","ts":1577430747.6640823,"logger":"baremetalhost_ironic","msg":"found existing node by ID","host":"node-0"}
{"level":"info","ts":1577430747.6643517,"logger":"baremetalhost_ironic","msg":"provisioning image to host","host":"node-0","state":"clean wait"}
E1227 07:12:27.664912       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 226 [running]:
github.com/metal3-io/baremetal-operator/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1379380, 0x2026980)
	/go/src/github.com/metal3-io/baremetal-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xaa
github.com/metal3-io/baremetal-operator/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/metal3-io/baremetal-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x1379380, 0x2026980)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/metal3-io/baremetal-operator/pkg/provisioner/ironic.(*ironicProvisioner).Provision(0xc420708f50, 0xc4207c3a40, 0xc, 0x0, 0x0, 0x0, 0x4122f8, 0x10)
	/go/src/github.com/metal3-io/baremetal-operator/pkg/provisioner/ironic/ironic.go:922 +0x156
github.com/metal3-io/baremetal-operator/pkg/controller/baremetalhost.(*ReconcileBareMetalHost).actionProvisioning(0xc420352040, 0x166ade0, 0xc420708f50, 0xc420708ee0, 0xf70000c4207bdbf0, 0xc4207bdbe0)
	/go/src/github.com/metal3-io/baremetal-operator/pkg/controller/baremetalhost/baremetalhost_controller.go:496 +0xdc
github.com/metal3-io/baremetal-operator/pkg/controller/baremetalhost.(*hostStateMachine).handleProvisioning(0xc4207cb3e0, 0xc420708ee0, 0xc4207bdb90, 0xc4207c4340)
	/go/src/github.com/metal3-io/baremetal-operator/pkg/controller/baremetalhost/host_state_machine.go:217 +0xb8
github.com/metal3-io/baremetal-operator/pkg/controller/baremetalhost.(*hostStateMachine).(github.com/metal3-io/baremetal-operator/pkg/controller/baremetalhost.handleProvisioning)-fm(0xc420708ee0, 0xc4207cb410, 0xc420049154)
	/go/src/github.com/metal3-io/baremetal-operator/pkg/controller/baremetalhost/host_state_machine.go:45 +0x34
github.com/metal3-io/baremetal-operator/pkg/controller/baremetalhost.(*hostStateMachine).ReconcileState(0xc4207cb3e0, 0xc420708ee0, 0x0, 0x0)
	/go/src/github.com/metal3-io/baremetal-operator/pkg/controller/baremetalhost/host_state_machine.go:80 +0x333
github.com/metal3-io/baremetal-operator/pkg/controller/baremetalhost.(*ReconcileBareMetalHost).Reconcile(0xc420352040, 0xc420048360, 0x6, 0xc420048330, 0x6, 0x2040b40, 0x4023d5, 0xc42075c1c0, 0x756ea168d23a89)
	/go/src/github.com/metal3-io/baremetal-operator/pkg/controller/baremetalhost/baremetalhost_controller.go:212 +0x7d9
github.com/metal3-io/baremetal-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc42044c9c0, 0x13c3ec0, 0xc42075c1c0, 0x13c3e00)
	/go/src/github.com/metal3-io/baremetal-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:256 +0x100
github.com/metal3-io/baremetal-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc42044c9c0, 0xc4200a6200)
	/go/src/github.com/metal3-io/baremetal-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:232 +0xb7
github.com/metal3-io/baremetal-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc42044c9c0)
	/go/src/github.com/metal3-io/baremetal-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:211 +0x2b
github.com/metal3-io/baremetal-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).(github.com/metal3-io/baremetal-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.worker)-fm()
	/go/src/github.com/metal3-io/baremetal-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:193 +0x2a
github.com/metal3-io/baremetal-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc4207bdae0)
	/go/src/github.com/metal3-io/baremetal-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x54
github.com/metal3-io/baremetal-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc4207bdae0, 0x3b9aca00, 0x0, 0x1, 0xc42026a120)
	/go/src/github.com/metal3-io/baremetal-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xbd
github.com/metal3-io/baremetal-operator/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc4207bdae0, 0x3b9aca00, 0xc42026a120)
	/go/src/github.com/metal3-io/baremetal-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/metal3-io/baremetal-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/go/src/github.com/metal3-io/baremetal-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:193 +0x63b
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xb3af96]

goroutine 226 [running]:
github.com/metal3-io/baremetal-operator/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/metal3-io/baremetal-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x107
panic(0x1379380, 0x2026980)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/metal3-io/baremetal-operator/pkg/provisioner/ironic.(*ironicProvisioner).Provision(0xc420708f50, 0xc4207c3a40, 0xc, 0x0, 0x0, 0x0, 0x4122f8, 0x10)
	/go/src/github.com/metal3-io/baremetal-operator/pkg/provisioner/ironic/ironic.go:922 +0x156
github.com/metal3-io/baremetal-operator/pkg/controller/baremetalhost.(*ReconcileBareMetalHost).actionProvisioning(0xc420352040, 0x166ade0, 0xc420708f50, 0xc420708ee0, 0xf70000c4207bdbf0, 0xc4207bdbe0)
	/go/src/github.com/metal3-io/baremetal-operator/pkg/controller/baremetalhost/baremetalhost_controller.go:496 +0xdc
github.com/metal3-io/baremetal-operator/pkg/controller/baremetalhost.(*hostStateMachine).handleProvisioning(0xc4207cb3e0, 0xc420708ee0, 0xc4207bdb90, 0xc4207c4340)
	/go/src/github.com/metal3-io/baremetal-operator/pkg/controller/baremetalhost/host_state_machine.go:217 +0xb8
github.com/metal3-io/baremetal-operator/pkg/controller/baremetalhost.(*hostStateMachine).(github.com/metal3-io/baremetal-operator/pkg/controller/baremetalhost.handleProvisioning)-fm(0xc420708ee0, 0xc4207cb410, 0xc420049154)
	/go/src/github.com/metal3-io/baremetal-operator/pkg/controller/baremetalhost/host_state_machine.go:45 +0x34
github.com/metal3-io/baremetal-operator/pkg/controller/baremetalhost.(*hostStateMachine).ReconcileState(0xc4207cb3e0, 0xc420708ee0, 0x0, 0x0)
	/go/src/github.com/metal3-io/baremetal-operator/pkg/controller/baremetalhost/host_state_machine.go:80 +0x333
github.com/metal3-io/baremetal-operator/pkg/controller/baremetalhost.(*ReconcileBareMetalHost).Reconcile(0xc420352040, 0xc420048360, 0x6, 0xc420048330, 0x6, 0x2040b40, 0x4023d5, 0xc42075c1c0, 0x756ea168d23a89)
	/go/src/github.com/metal3-io/baremetal-operator/pkg/controller/baremetalhost/baremetalhost_controller.go:212 +0x7d9
github.com/metal3-io/baremetal-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc42044c9c0, 0x13c3ec0, 0xc42075c1c0, 0x13c3e00)
	/go/src/github.com/metal3-io/baremetal-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:256 +0x100
github.com/metal3-io/baremetal-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc42044c9c0, 0xc4200a6200)
	/go/src/github.com/metal3-io/baremetal-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:232 +0xb7
github.com/metal3-io/baremetal-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc42044c9c0)
	/go/src/github.com/metal3-io/baremetal-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:211 +0x2b
github.com/metal3-io/baremetal-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).(github.com/metal3-io/baremetal-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.worker)-fm()
	/go/src/github.com/metal3-io/baremetal-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:193 +0x2a
github.com/metal3-io/baremetal-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc4207bdae0)
	/go/src/github.com/metal3-io/baremetal-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x54
github.com/metal3-io/baremetal-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc4207bdae0, 0x3b9aca00, 0x0, 0x1, 0xc42026a120)
	/go/src/github.com/metal3-io/baremetal-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xbd
github.com/metal3-io/baremetal-operator/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc4207bdae0, 0x3b9aca00, 0xc42026a120)
	/go/src/github.com/metal3-io/baremetal-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/metal3-io/baremetal-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/go/src/github.com/metal3-io/baremetal-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:193 +0x63b

```

**Comment by dhellmann** [comment]
It looks like the state machine isn't handling the case where we want to delete a host that has no image. The line in ironic.go is trying to access the checksum (https://github.com/metal3-io/baremetal-operator/blob/master/pkg/provisioner/ironic/ironic.go#L922) from within the Provision() method, and we probably shouldn't be calling Provision() on a host we're deleting.

**Comment by zaneb** [comment]
Looks like the same issue as #342.

**Comment by zaneb** [comment]
OK, I think I found the problem. If you cancel provisioning before it has finished, both `NeedsProvisioning()` and `NeedsDeprovisioning()` return `false` because the latter assumes that provisioning has to be complete before the host needs to be deprovisioned.

Prior to introducing the state machine, this was necessary because otherwise the Host would never reach the Ready state as the operator would always be trying to deprovision it. There was still a bug in this scenario, because it looks like it would have just pushed the Host straight back to the Ready state (without actually deprovisioning it) when provisioning was cancelled.

Because the state machine remembers the state, it tries to continue provisioning (if it ever finished it would move on to deprovisioning, but it doesn't). This results in a crash because the Ironic provisioner assumes (quite reasonably) that the Image is non-null when we are trying to provision.
