### ISSUE TITLE
Issue in enabling ilo hardware type

### ISSUE THREAD

**Issue by ankit-kumar5** [metal3-io/baremetal-operator#598]
Hi 

I am working on enablement of ilo hardware type. And i am facing one issue when i am adding ilo hardware type in enabled_hardware_types (/etc/ironic/ironic.conf). This is the error i am getting 

**ERROR:**
=====

/usr/lib/python3.6/site-packages/oslo_serialization/jsonutils.py:180: UserWarning: Cannot convert <ironic.drivers.modules.ipxe.iPXEBoot object at 0x7fbca2dd5e10> to primitive, will raise ValueError instead of warning in version 3.0
  "instead of warning in version 3.0" % (value,))
ERROR oslo_service.service [req-4243a8de-19fc-4688-936d-61312ec4091b - - - - -] Error starting thread.: ironic.common.exception.IncompatibleInterface: boot interface implementation '<ironic.drivers.modules.ipxe.iPXEBoot object at 0x7fbca2dd5e10>' is not supported by hardware type IloHardware.
ERROR oslo_service.service Traceback (most recent call last):
ERROR oslo_service.service   File "/usr/lib/python3.6/site-packages/oslo_service/service.py", line 807, in run_service
ERROR oslo_service.service     service.start()
ERROR oslo_service.service   File "/usr/lib/python3.6/site-packages/ironic/common/rpc_service.py", line 61, in start
ERROR oslo_service.service     self.manager.init_host(admin_context)
ERROR oslo_service.service   File "/usr/lib/python3.6/site-packages/ironic/conductor/base_manager.py", line 166, in init_host
ERROR oslo_service.service     self._register_and_validate_hardware_interfaces(hardware_types)
ERROR oslo_service.service   File "/usr/lib/python3.6/site-packages/ironic/conductor/base_manager.py", line 355, in _register_and_validate_hardware_interfaces
ERROR oslo_service.service     ht, interface_type, driver_name=ht_name)
ERROR oslo_service.service   File "/usr/lib/python3.6/site-packages/ironic/common/driver_factory.py", line 140, in default_interface
ERROR oslo_service.service     get_interface(hw_type, interface_type, impl_name)
ERROR oslo_service.service   File "/usr/lib/python3.6/site-packages/ironic/common/driver_factory.py", line 111, in get_interface
ERROR oslo_service.service     hardware_type=hw_type.__class__.__name__)
ERROR oslo_service.service ironic.common.exception.IncompatibleInterface: boot interface implementation '<**ironic.drivers.modules.ipxe.iPXEBoot object at 0x7fbca2dd5e10>' is not supported by hardware type IloHardware.**
ERROR oslo_service.service
INFO oslo.service.wsgi [-] Stopping WSGI server.
======================================

This is because ilo hardware type does not boot interface pxe or ipxe and in ironic.conf default_boot_interface is defined (which is ipxe). I try to remove the default_boot_interface and run the ironic service and it ran successfully. 

Why do we add this(default_boot_interface)?

**Comment by dhellmann** [comment]
The host is supposed to be registered with ironic using the boot interface specified by the BMC. See https://github.com/metal3-io/baremetal-operator/blob/master/pkg/provisioner/ironic/ironic.go#L245

If you look at the node in ironic, does it have the right boot interface set?

**Comment by ankit-kumar5** [comment]
Actually for every driver, boot interface is defined (For Ex: https://github.com/metal3-io/baremetal-operator/blob/master/pkg/bmc/redfish.go#L110)

In my case if i am adding hardware_type ilo, then ir-cond fails to start with the above error. It is not reaching to that point where node creation can happen since **ilo** doesn't support ipxe boot interface and its being set in default_boot_interface.

**Comment by dhellmann** [comment]
It sounds like you are saying that the ironic-conductor will not start because a default value, which we don't use, is incompatible with one of the drivers. Is that right?

@dtantsur @juliakreger do you have any insight on this? Should we remove the default boot interface setting, or choose a different one?

**Comment by juliakreger** [comment]
Greetings,

@ankit-kumar5 You'll need to set the boot interface to the special ilo-ipxe wrapper.... or just get rid of the interface wrapper and declare support for the stock ipxe driver.

https://github.com/openstack/ironic/blob/master/ironic/drivers/ilo.py#L41
https://github.com/openstack/ironic/blob/master/setup.cfg#L70

**Comment by ankit-kumar5** [comment]
> It sounds like you are saying that the ironic-conductor will not start because a default value, which we don't use, is incompatible with one of the drivers. Is that right?
> 
> @dtantsur @juliakreger do you have any insight on this? Should we remove the default boot interface setting, or choose a different one?

Yeah.. i am saying that only.

**Comment by ankit-kumar5** [comment]
> Greetings,
> 
> @ankit-kumar5 You'll need to set the boot interface to the special ilo-ipxe wrapper.... or just get rid of the interface wrapper and declare support for the stock ipxe driver.
> 
> https://github.com/openstack/ironic/blob/master/ironic/drivers/ilo.py#L41
> https://github.com/openstack/ironic/blob/master/setup.cfg#L70

I tried the first approach declaring ilo-ipxe as default_boot_interface and it failed because ilo-ipxe is not supported by other hardware types which is obvious that it fails. 
For the second approach, i can do that. I was just confirming whether default_boot_interface can be removed from the config or not.

**Comment by ankit-kumar5** [comment]
> > Greetings,
> > @ankit-kumar5 You'll need to set the boot interface to the special ilo-ipxe wrapper.... or just get rid of the interface wrapper and declare support for the stock ipxe driver.
> > https://github.com/openstack/ironic/blob/master/ironic/drivers/ilo.py#L41
> > https://github.com/openstack/ironic/blob/master/setup.cfg#L70
> 
> Sorry i didnt quite understand by **set the boot interface to the special ilo-ipxe wrapper** . By this you means setting the default_boot_interface. Am i correct?

I tried the first approach declaring ilo-ipxe as default_boot_interface and it failed because ilo-ipxe is not supported by other hardware types which is obvious that it fails.
> For the second approach, i can do that. I was just confirming whether default_boot_interface can be removed from the config or not.

**Comment by dhellmann** [comment]
We need to be able to add drivers without the user having to customize the default boot interface. If they have to change the default, it's not really a default.

Why won't conductor start with the default set the way it is now?

**Comment by ankit-kumar5** [comment]
> We need to be able to add drivers without the user having to customize the default boot interface. If they have to change the default, it's not really a default.
> 
> Why won't conductor start with the default set the way it is now?

Because this default(ipxe) is not supported by ilo hardware type, thats why its failing.

**Comment by dhellmann** [comment]
Why does ironic care if the default isn't supported by all of the drivers? Why not wait to fail at the point where the boot interface and driver for a given host are both known to be incompatible?

**Comment by ankit-kumar5** [comment]
> We need to be able to add drivers without the user having to customize the default boot interface. If they have to change the default, it's not really a default.
> 
> Why won't conductor start with the default set the way it is now?

I will make changes to ilo drivers to support ipxe and pxe boot interfaces.

**Comment by juliakreger** [comment]
So a few different thoughts:
1) Default is only if a node is created with just a "driver" field, and no other specific interface choices. It is handy, but I'm 99.95% sure the operator, when defining nodes allows all of the interfaces to be defined. If the operator is doing this in two steps against the API, that is likely not ideal.
2) If the list of enabled hardware types includes priority, where the preferred default is the first element in that list, then the "default" can be completely removed. The union of enabled and supported interfaces by the driver will choose the one to use in order of highest to lowest priority.

What I meant by set the boot interface to ilo-ipxe, was to actually do that in the baremetal operator. Similar to how redfish-virtual-media works. See: https://github.com/metal3-io/baremetal-operator/blob/master/pkg/bmc/redfish.go#L132

**Comment by ankit-kumar5** [comment]
> So a few different thoughts:
> 
> 1. Default is only if a node is created with just a "driver" field, and no other specific interface choices. It is handy, but I'm 99.95% sure the operator, when defining nodes allows all of the interfaces to be defined. If the operator is doing this in two steps against the API, that is likely not ideal.
> 2. If the list of enabled hardware types includes priority, where the preferred default is the first element in that list, then the "default" can be completely removed. The union of enabled and supported interfaces by the driver will choose the one to use in order of highest to lowest priority.
> 
> What I meant by set the boot interface to ilo-ipxe, was to actually do that in the baremetal operator. Similar to how redfish-virtual-media works. See: https://github.com/metal3-io/baremetal-operator/blob/master/pkg/bmc/redfish.go#L132

I have been doing this. You can see here 
https://github.com/metal3-io/baremetal-operator/pull/595/commits/ba6dc38e8a3a28b07c18c31b965fefcca2435a60#diff-ce770aa06cd9fa55727a51d6584280b1R70

But its failing way before executing this, when i am adding in conf file(/etc/ironic/ironic.conf)

default_boot_interface = ipxe
default_deploy_interface = direct
default_inspect_interface = inspector
default_network_interface = noop
enabled_boot_interfaces = pxe,ipxe,fake,redfish-virtual-media,idrac-redfish-virtual-media,**ilo-ipxe**
enabled_deploy_interfaces = direct,fake
enabled_hardware_types = ipmi,idrac,irmc,fake-hardware,redfish,ibmc,**ilo**
enabled_inspect_interfaces = inspector,idrac,irmc,fake,redfish
enabled_management_interfaces = ipmitool,idrac,irmc,fake,redfish,idrac-redfish,ibmc,**ilo**
enabled_power_interfaces = ipmitool,idrac,irmc,fake,redfish,idrac-redfish,ibmc,**ilo**
enabled_raid_interfaces = no-raid,irmc,agent,fake
enabled_vendor_interfaces = ipmitool,no-vendor,idrac,fake,ibmc,**ilo**

**Comment by juliakreger** [comment]
Remove the default_boot_interface line, and change the enabled_boot_interfaces to:

enabled_boot_interfaces = ipxe,pxe,fake,redfish-virtual-media,idrac-redfish-virtual-media,ilo-ipxe

It will have the same effective configuration for all users and you'll be able to explicitly ask for ilo-ipxe.

**Comment by ankit-kumar5** [comment]
> Remove the default_boot_interface line, and change the enabled_boot_interfaces to:
> 
> enabled_boot_interfaces = ipxe,pxe,fake,redfish-virtual-media,idrac-redfish-virtual-media,ilo-ipxe
> 
> It will have the same effective configuration for all users and you'll be able to explicitly ask for ilo-ipxe.

Thanks @juliakreger.. I was asking for this clarification only.
