### ISSUE TITLE
bootloader

### ISSUE THREAD

**Issue by jplimack** [metal3-io/baremetal-operator#992]
Having some issues provisioning OS onto nodes.  I'm using `image-builder` to construct the qcow2 image, but its failing to find EFI data.  I attempted to rebuild the image with a boot/ept partition, but to no avail.  Any advice on debugging would be greatly appreciated

```
Oct 08 18:51:47 localhost.localdomain ironic-python-agent[2899]: 2021-10-08 18:51:47.110 2899 INFO ironic_lib.utils [-] Root device found! The device "{'name': '/dev/sda', 'model': 'Micron_1300_MTFD', 'size': 512110190592, 'rotational': False, 'wwn': '0x500a07512efca90a', 'serial': '21112EFCA90A', 'vendor': 'ATA', 'wwn_with_extension': '0x500a07512efca90a', 'wwn_vendor_extension': None, 'hctl': '4:0:0:0', 'by_path': '/dev/disk/by-path/pci-0000:00:11.5-ata-5'}" matches the root device hints {'name': 's== /dev/sda'}
Oct 08 18:51:47 localhost.localdomain ironic-python-agent[2899]: 2021-10-08 18:51:47.110 2899 INFO root [-] Picked root device /dev/sda for node 87434412-a3ea-4eef-8197-99efd20101c2 based on root device hints {'name': 's== /dev/sda'}
Oct 08 18:51:47 localhost.localdomain ironic-python-agent[2899]: 2021-10-08 18:51:47.110 2899 DEBUG root [-] HardwareManager <ironic_python_agent.hardware_managers.mlnx.MellanoxDeviceHardwareManager object at 0x7f6d7fc0b630> does not support get_boot_info dispatch_to_managers /usr/lib/python3.6/site-packages/ironic_python_agent/hardware.py:2588
Oct 08 18:51:47 localhost.localdomain ironic-python-agent[2899]: 2021-10-08 18:51:47.110 2899 DEBUG root [-] The current boot mode is bios get_boot_info /usr/lib/python3.6/site-packages/ironic_python_agent/hardware.py:1272
Oct 08 18:51:47 localhost.localdomain ironic-python-agent[2899]: 2021-10-08 18:51:47.111 2899 WARNING ironic_python_agent.extensions.image [-] Boot mode mismatch: target boot mode is uefi, current boot mode is bios. Installing boot loader may fail or work incorrectly.
Oct 08 18:51:47 localhost.localdomain ironic-python-agent[2899]: 2021-10-08 18:51:47.111 2899 DEBUG ironic_python_agent.extensions.image [-] Using grub2-install to set up boot files install_bootloader /usr/lib/python3.6/site-packages/ironic_python_agent/extensions/image.py:1109
Oct 08 18:51:47 localhost.localdomain ironic-python-agent[2899]: 2021-10-08 18:51:47.111 2899 DEBUG ironic_python_agent.extensions.image [-] Installing GRUB2 bootloader on device /dev/sda _install_grub2 /usr/lib/python3.6/site-packages/ironic_python_agent/extensions/image.py:584
Oct 08 18:51:47 localhost.localdomain ironic-python-agent[2899]: 2021-10-08 18:51:47.111 2899 DEBUG ironic_python_agent.extensions.image [-] Find the partition 0x1d1eb768 on device /dev/sda _get_partition /usr/lib/python3.6/site-packages/ironic_python_agent/extensions/image.py:76
Oct 08 18:51:51 localhost.localdomain ironic-python-agent[2899]: 2021-10-08 18:51:47.111 2899 DEBUG oslo_concurrency.processutils [-] Running cmd (subprocess): partx -u /dev/sda execute /usr/lib/python3.6/site-packages/oslo_concurrency/processutils.py:384
Oct 08 18:51:51 localhost.localdomain ironic-python-agent[2899]: 2021-10-08 18:51:49.125 2899 INFO eventlet.wsgi.server [-] ::ffff:10.168.163.26 "GET /v1/commands/ HTTP/1.1" status: 200  len: 107115 time: 0.0009141
Oct 08 18:51:51 localhost.localdomain ironic-python-agent[2899]: 2021-10-08 18:51:51.106 2899 DEBUG oslo_concurrency.processutils [-] CMD "partx -u /dev/sda" returned: 0 in 3.995s execute /usr/lib/python3.6/site-packages/oslo_concurrency/processutils.py:423
Oct 08 18:51:51 localhost.localdomain ironic-python-agent[2899]: 2021-10-08 18:51:51.106 2899 DEBUG ironic_lib.utils [-] Command stdout is: "" _log /usr/lib/python3.6/site-packages/ironic_lib/utils.py:99
Oct 08 18:51:51 localhost.localdomain ironic-python-agent[2899]: 2021-10-08 18:51:51.106 2899 DEBUG ironic_lib.utils [-] Command stderr is: "" _log /usr/lib/python3.6/site-packages/ironic_lib/utils.py:100
Oct 08 18:51:51 localhost.localdomain ironic-python-agent[2899]: 2021-10-08 18:51:51.106 2899 DEBUG oslo_concurrency.processutils [-] Running cmd (subprocess): udevadm settle execute /usr/lib/python3.6/site-packages/oslo_concurrency/processutils.py:384
Oct 08 18:51:51 localhost.localdomain ironic-python-agent[2899]: 2021-10-08 18:51:51.119 2899 DEBUG oslo_concurrency.processutils [-] CMD "udevadm settle" returned: 0 in 0.013s execute /usr/lib/python3.6/site-packages/oslo_concurrency/processutils.py:423
Oct 08 18:51:51 localhost.localdomain ironic-python-agent[2899]: 2021-10-08 18:51:51.120 2899 DEBUG ironic_lib.utils [-] Command stdout is: "" _log /usr/lib/python3.6/site-packages/ironic_lib/utils.py:99
Oct 08 18:51:51 localhost.localdomain ironic-python-agent[2899]: 2021-10-08 18:51:51.120 2899 DEBUG ironic_lib.utils [-] Command stderr is: "" _log /usr/lib/python3.6/site-packages/ironic_lib/utils.py:100
Oct 08 18:51:51 localhost.localdomain ironic-python-agent[2899]: 2021-10-08 18:51:51.120 2899 DEBUG oslo_concurrency.processutils [-] Running cmd (subprocess): lsblk -PbioKNAME,UUID,PARTUUID,TYPE,LABEL /dev/sda execute /usr/lib/python3.6/site-packages/oslo_concurrency/processutils.py:384
Oct 08 18:51:51 localhost.localdomain ironic-python-agent[2899]: 2021-10-08 18:51:51.125 2899 DEBUG oslo_concurrency.processutils [-] CMD "lsblk -PbioKNAME,UUID,PARTUUID,TYPE,LABEL /dev/sda" returned: 0 in 0.004s execute /usr/lib/python3.6/site-packages/oslo_concurrency/processutils.py:423
Oct 08 18:51:51 localhost.localdomain ironic-python-agent[2899]: 2021-10-08 18:51:51.125 2899 DEBUG ironic_lib.utils [-] Command stdout is: "KNAME="sda" UUID="" PARTUUID="" TYPE="disk" LABEL=""
                                                                 KNAME="sda1" UUID="23d9d143-4eb6-42be-a2df-986cd3e2c27c" PARTUUID="1d1eb768-01" TYPE="part" LABEL=""
                                                                 KNAME="sda2" UUID="2021-10-08-18-48-03-00" PARTUUID="1d1eb768-02" TYPE="part" LABEL="config-2"
                                                                 " _log /usr/lib/python3.6/site-packages/ironic_lib/utils.py:99
Oct 08 18:51:51 localhost.localdomain ironic-python-agent[2899]: 2021-10-08 18:51:51.125 2899 DEBUG ironic_lib.utils [-] Command stderr is: "" _log /usr/lib/python3.6/site-packages/ironic_lib/utils.py:100
Oct 08 18:51:51 localhost.localdomain ironic-python-agent[2899]: 2021-10-08 18:51:51.125 2899 DEBUG oslo_concurrency.processutils [-] Running cmd (subprocess): findfs UUID=0x1d1eb768 execute /usr/lib/python3.6/site-packages/oslo_concurrency/processutils.py:384
Oct 08 18:51:51 localhost.localdomain ironic-python-agent[2899]: 2021-10-08 18:51:51.141 2899 DEBUG oslo_concurrency.processutils [-] CMD "findfs UUID=0x1d1eb768" returned: 1 in 0.015s execute /usr/lib/python3.6/site-packages/oslo_concurrency/processutils.py:423
Oct 08 18:51:51 localhost.localdomain ironic-python-agent[2899]: 2021-10-08 18:51:51.141 2899 DEBUG oslo_concurrency.processutils [-] 'findfs UUID=0x1d1eb768' failed. Not Retrying. execute /usr/lib/python3.6/site-packages/oslo_concurrency/processutils.py:474
Oct 08 18:51:51 localhost.localdomain ironic-python-agent[2899]: 2021-10-08 18:51:51.141 2899 DEBUG ironic_lib.utils [-] Command stdout is: "" _log /usr/lib/python3.6/site-packages/ironic_lib/utils.py:99
Oct 08 18:51:51 localhost.localdomain ironic-python-agent[2899]: 2021-10-08 18:51:51.141 2899 DEBUG ironic_lib.utils [-] Command stderr is: "findfs: unable to resolve 'UUID=0x1d1eb768'
                                                                 " _log /usr/lib/python3.6/site-packages/ironic_lib/utils.py:100
Oct 08 18:51:55 localhost.localdomain ironic-python-agent[2899]: 2021-10-08 18:51:51.141 2899 DEBUG ironic_python_agent.extensions.image [-] First fallback detection attempt for locating partition via UUID 0x1d1eb768 failed. Error: Unexpected error while running command.
                                                                 Command: findfs UUID=0x1d1eb768
                                                                 Exit code: 1
                                                                 Stdout: ''
                                                                 Stderr: "findfs: unable to resolve 'UUID=0x1d1eb768'\n" _get_partition /usr/lib/python3.6/site-packages/ironic_python_agent/extensions/image.py:121
Oct 08 18:51:55 localhost.localdomain ironic-python-agent[2899]: 2021-10-08 18:51:55.128 2899 DEBUG oslo_concurrency.processutils [-] Running cmd (subprocess): findfs PARTUUID=0x1d1eb768 execute /usr/lib/python3.6/site-packages/oslo_concurrency/processutils.py:384
Oct 08 18:51:55 localhost.localdomain ironic-python-agent[2899]: 2021-10-08 18:51:55.143 2899 DEBUG oslo_concurrency.processutils [-] CMD "findfs PARTUUID=0x1d1eb768" returned: 1 in 0.015s execute /usr/lib/python3.6/site-packages/oslo_concurrency/processutils.py:423
Oct 08 18:51:55 localhost.localdomain ironic-python-agent[2899]: 2021-10-08 18:51:55.143 2899 DEBUG oslo_concurrency.processutils [-] 'findfs PARTUUID=0x1d1eb768' failed. Not Retrying. execute /usr/lib/python3.6/site-packages/oslo_concurrency/processutils.py:474
Oct 08 18:51:55 localhost.localdomain ironic-python-agent[2899]: 2021-10-08 18:51:55.144 2899 DEBUG ironic_lib.utils [-] Command stdout is: "" _log /usr/lib/python3.6/site-packages/ironic_lib/utils.py:99
Oct 08 18:51:55 localhost.localdomain ironic-python-agent[2899]: 2021-10-08 18:51:55.144 2899 DEBUG ironic_lib.utils [-] Command stderr is: "findfs: unable to resolve 'PARTUUID=0x1d1eb768'
                                                                 " _log /usr/lib/python3.6/site-packages/ironic_lib/utils.py:100
Oct 08 18:51:55 localhost.localdomain ironic-python-agent[2899]: 2021-10-08 18:51:55.144 2899 DEBUG ironic_python_agent.extensions.image [-] Secondary fallback detection attempt for locating partition via UUID 0x1d1eb768 failed. Error: Unexpected error while running command.
                                                                 Command: findfs PARTUUID=0x1d1eb768
                                                                 Exit code: 1
                                                                 Stdout: ''
                                                                 Stderr: "findfs: unable to resolve 'PARTUUID=0x1d1eb768'\n" _get_partition /usr/lib/python3.6/site-packages/ironic_python_agent/extensions/image.py:131
Oct 08 18:51:55 localhost.localdomain ironic-python-agent[2899]: 2021-10-08 18:51:55.144 2899 DEBUG oslo_concurrency.processutils [-] Running cmd (subprocess): mdadm --detail /dev/sda execute /usr/lib/python3.6/site-packages/oslo_concurrency/processutils.py:384
Oct 08 18:51:55 localhost.localdomain ironic-python-agent[2899]: 2021-10-08 18:51:55.147 2899 INFO eventlet.wsgi.server [-] ::ffff:10.168.163.26 "GET /v1/commands/ HTTP/1.1" status: 200  len: 107115 time: 0.0022254
Oct 08 18:51:55 localhost.localdomain ironic-python-agent[2899]: 2021-10-08 18:51:55.149 2899 DEBUG oslo_concurrency.processutils [-] CMD "mdadm --detail /dev/sda" returned: 1 in 0.005s execute /usr/lib/python3.6/site-packages/oslo_concurrency/processutils.py:423
Oct 08 18:51:55 localhost.localdomain ironic-python-agent[2899]: 2021-10-08 18:51:55.150 2899 DEBUG oslo_concurrency.processutils [-] 'mdadm --detail /dev/sda' failed. Not Retrying. execute /usr/lib/python3.6/site-packages/oslo_concurrency/processutils.py:474
Oct 08 18:51:55 localhost.localdomain ironic-python-agent[2899]: 2021-10-08 18:51:55.150 2899 DEBUG ironic_lib.utils [-] Command stdout is: "" _log /usr/lib/python3.6/site-packages/ironic_lib/utils.py:99
Oct 08 18:51:55 localhost.localdomain ironic-python-agent[2899]: 2021-10-08 18:51:55.150 2899 DEBUG ironic_lib.utils [-] Command stderr is: "mdadm: /dev/sda does not appear to be an md device
                                                                 " _log /usr/lib/python3.6/site-packages/ironic_lib/utils.py:100
Oct 08 18:51:55 localhost.localdomain ironic-python-agent[2899]: 2021-10-08 18:51:55.150 2899 DEBUG root [-] /dev/sda is not an md device is_md_device /usr/lib/python3.6/site-packages/ironic_python_agent/hardware.py:314
Oct 08 18:51:55 localhost.localdomain ironic-python-agent[2899]: 2021-10-08 18:51:55.150 2899 ERROR ironic_python_agent.extensions.image [-] No partition with UUID 0x1d1eb768 found on device /dev/sda
Oct 08 18:51:55 localhost.localdomain ironic-python-agent[2899]: 2021-10-08 18:51:55.150 2899 ERROR ironic_python_agent.extensions.image [-] Error setting up bootloader. Error Error finding the disk or partition device to deploy the image onto: No partition with UUID 0x1d1eb768 found on device /dev/sda: ironic_python_agent.errors.DeviceNotFound: Error finding the disk or partition device to deploy the image onto: No partition with UUID 0x1d1eb768 found on device /dev/sda
Oct 08 18:51:59 localhost.localdomain ironic-python-agent[2899]: 2021-10-08 18:51:55.152 2899 ERROR root [-] Command failed: install_bootloader, error: Error finding the disk or partition device to deploy the image onto: No partition with UUID 0x1d1eb768 found on device /dev/sda: ironic_python_agent.errors.DeviceNotFound: Error finding the disk or partition device to deploy the image onto: No partition with UUID 0x1d1eb768 found on device /dev/sda
                                                                 2021-10-08 18:51:55.152 2899 ERROR root Traceback (most recent call last):
                                                                 2021-10-08 18:51:55.152 2899 ERROR root   File "/usr/lib/python3.6/site-packages/ironic_python_agent/extensions/base.py", line 174, in run
                                                                 2021-10-08 18:51:55.152 2899 ERROR root     result = self.execute_method(**self.command_params)
                                                                 2021-10-08 18:51:55.152 2899 ERROR root   File "/usr/lib/python3.6/site-packages/ironic_python_agent/extensions/image.py", line 1115, in install_bootloader
                                                                 2021-10-08 18:51:55.152 2899 ERROR root     target_boot_mode=target_boot_mode)
                                                                 2021-10-08 18:51:55.152 2899 ERROR root   File "/usr/lib/python3.6/site-packages/ironic_python_agent/extensions/image.py", line 597, in _install_grub2
                                                                 2021-10-08 18:51:55.152 2899 ERROR root     root_partition = _get_partition(device, uuid=root_uuid)
                                                                 2021-10-08 18:51:55.152 2899 ERROR root   File "/usr/lib/python3.6/site-packages/ironic_python_agent/extensions/image.py", line 153, in _get_partition
                                                                 2021-10-08 18:51:55.152 2899 ERROR root     raise errors.DeviceNotFound(error_msg)
                                                                 2021-10-08 18:51:55.152 2899 ERROR root ironic_python_agent.errors.DeviceNotFound: Error finding the disk or partition device to deploy the image onto: No partition with UUID 0x1d1eb768 found on device /dev/sda
                                                                 2021-10-08 18:51:55.152 2899 ERROR root
```

**Comment by yanndegat** [comment]
hi @jplimack 

did you manage to get around it ? i'm currently stuck with the same issue.

**Comment by Rozzii** [comment]
/remove-triage/accepted
